### ISSUE TITLE
文件

### ISSUE THREAD

**Issue by sih4sing5hong5** [sih4sing5hong5/PlanB#1]
```


Traceback (most recent call last):
  File "./compiler_scripts/image_build.py", line 111, in <module>
    process_file_to_atlas()
  File "./compiler_scripts/image_build.py", line 101, in process_file_to_atlas
    ignore_exceptions=args.ignoreexceptions, generate_mips=True) #, no_premultiply=im.mode=='RGB' )
  File "/home/ciciw/.local/share/Steam/steamapps/common/Don't Starve Together/mod_tools/mod_tools/buildtools/linux/Python27/Lib/site-packages/klei/textureconverter.py", line 113, in Convert
    if subprocess.call( cmd_list ) != 0:
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ERROR: Command failed!

```
https://github.com/kleientertainment/ds_mod_tools

https://github.com/nsimplex/ktools

```

sudo apt-get install cmake libmagick++-dev
./configure && make
sudo cp ktech /usr/local/bin

```

**Comment by sih4sing5hong5** [comment]
/home/ciciw/.local/share/Steam/steamapps/common/Don't Starve Together/mods/sui2-361202313

**Comment by a8568730** [comment]
```bash
# Step 1. Manually build a dependency (ktools) for step 2 
$ cd ~/git
$ git clone git@github.com:nsimplex/ktools.git
$ sudo apt-get install cmake libmagick++-dev
$ cd ./ktools
$ ./configure && make
$ sudo make install

$ cd ~/git
$ git clone git@github.com:kleientertainment/ds_mod_tools.git
$ sudo apt-get install premake4

$ cd ~/git/ds_mod_tools/src
$ bash premake.sh

$ cd ~/git/ds_mod_tools/build/proj
$ make

$ cp  -r ~/git/ds_mod_tools/build/linux/ ~/.local/share/Steam/steamapps/common/Don\'t\ Starve\ Together

$ cd ~/.local/share/Steam/steamapps/common/Don\'t\ Starve\ Together/mods
# Copy your mod directory
$ cp  -r ~/git/MySampleCharacter/ ~/.local/share/Steam/steamapps/common/Don\'t\ Starve\ Together
 

$ cd ~/.local/share/Steam/steamapps/common/Don\'t\ Starve\ Together/linux/mod_tools
$ ./autocompiler
```

**Comment by a8568730** [comment]
```bash
# NOTE:
# {DST_ROOT} means the DST root directory: 
# ~/.local/share/Steam/steamapps/common/Don\'t\ Starve\ Together/
```
Step. Install and clone tools
```bash
$ cd {DST_ROOT}
$ sudo apt-get install cmake libmagick++-dev 
$ sudo apt-get install premake4 
$ git clone git@github.com:nsimplex/ktools.git
$ git clone git@github.com:kleientertainment/ds_mod_tools.git
```
Step. Build and install ktools
```bash
$ cd ./ktools/
$ ./configure && make
$ sudo make install
```
Step. Build ds_mod_tools autocompiler
```bash
$ cd ../ds_mod_tools/src/
$ bash premake.sh
$ cd ../build/proj/
$ make
```
Step. Copy autocompiler to DST_ROOT
```bash
$ cd ../
$ cp  -r ./linux {DST_ROOT}
```
Step. Copy your mod directory to DST_ROOT
```bash
$ cp  -r ~/home/MyCharacter/ {DST_ROOT}/mods
```
Step. Rock!
```bash

$ cd {DST_ROOT}/linux/mod_tools/
$ ./autocompiler
```
